### ISSUE TITLE
How to return an object from the managed code?

### ISSUE THREAD

**Issue by samikrc** [jsuereth/scala-arm#114]
Not sure how to put the question in a better way, so here goes: from a database query, I want to pick up a single value. But I am not able to get the value to return from the enclosing method.
```
def getResult[T]: T =
{
        for(
            conn <- managed(MySQLBackend.getConnection);
            pst <- managed(
            {
                val myst = conn.prepareStatement(query))
                params.zipWithIndex.foreach{ case (value, i) => addParam(myst, i, value) }
                myst
            });
            rs <- managed(pst.executeQuery())
        ) yield
        {
            rs.last()
            val result = rs.getObject(0).asInstanceOf[T]
            //***** Now how do I return result from the getResult method? *************
            //***** Outside of the block, I get ManagedResource[T]
            result
        }
}
```

**Comment by cchantep** [comment]
Using `acquireAndGet`

**Comment by samikrc** [comment]
Thanks for the hint - that worked. Had to rewrite the code like this:
```
       val mresultset = for
            (
                conn <- managed(MySQLBackend.getConnection);
                pst <- managed(
                {
                    val myst = conn.prepareStatement(query))
                    params.zipWithIndex.foreach{ case (value, i) => addParam(myst, i, value) }
                    myst
                });
                rs <- managed(pst.executeQuery())
            ) yield rs

        val result = mresultset.acquireAndGet
        { rs => if(rs.next()) Some(rs.getObject(0).asInstanceOf[T]) else None   }
```

**Comment by samikrc** [comment]
Actually, wanted to keep this open, to check if the code above is the correct way of doing this. Would the acquireAndGet method both get the result and close all the managed resources above? In here, there are 3 managed resources (conn , pst, rs), each of which has a close() method.

**Comment by cchantep** [comment]
GitHub issue is not for asking question/for help.
You can use [SO](stackoverflow.com/) for that purpose. Thanks.

**Comment by samikrc** [comment]
@cchantep Fair enough - although would have appreciated a quick response as well in the spirit of community. Thanks for the pointer though. Best.
