### ISSUE TITLE
Resource of HttpURLConnection

### ISSUE THREAD

**Issue by cchantep** [jsuereth/scala-arm#24]
Hi,

It would be nice to be able to use scala-arm with HttpURLConnection . It doesn't provide a close method, but a disconnect one:

```scala
  implicit def HttpURLConnectionResource: Resource[HttpURLConnection] =
    new Resource[HttpURLConnection] {
      def close(c: HttpURLConnection) = c.disconnect()
    }
```

(or maybe some more generic typeclass)

**Comment by jsuereth** [comment]
Will do! Thanks for reporting.
