### ISSUE TITLE
Please consider using Java 7's “suppressed exceptions” mechanism

### ISSUE THREAD

**Issue by argv-minus-one** [jsuereth/scala-arm#36]
In several places, scala-arm returns an `Either[Iterable[Throwable], _]`, containing either all the exceptions it caught, or a successful result.

As of Java 7, this is unnecessary: its `Throwable` class has an `addSuppressed` method for handling this same kind of situation. Since the Scala community seems to have decided to drop support for Java < 8 in the next major Scala release, and since this “suppressed exceptions” mechanism is far more elegant than using `Either` like this, I hope you'll consider using it in scala-arm.

**Comment by jsuereth** [comment]
Hmm... yeah.  I think I would like to use it.  I may sneak this into the code where we convert form Either[Iterable[Thorwable], T] => T (like acquireAndGet).

**Comment by argv-minus-one** [comment]
If you do that, by the way, you also could switch to using `Try` instead of `Either`, since you won't have to return more than one exception any more.

**Comment by jsuereth** [comment]
So it looks like, due to issues people have had with suppressed exceptions, this will most likely be a "compatibility shim" rather than how we do things under the covers.

**Comment by jsuereth** [comment]
This should be the case in 2.0-RC1

**Comment by argv-minus-one** [comment]
Well, that's disappointing. What issues?
