### ISSUE TITLE
Scala Try instead of Either

### ISSUE THREAD

**Issue by nlhkh** [jsuereth/scala-arm#40]
As of Scala 2.10, Try is preferred to Either for handling exception because with Try, Failure is failure, and Success is success, where as with Either, Left or Right can be anything.

**Comment by jsuereth** [comment]
We can probably get this change in for 2.0

**Comment by pollycchang** [comment]
I'd like to see this as well. Thanks!

**Comment by jsuereth** [comment]
So we have Try support for 2.0, but we'll still be using Either internally so we can merge/group collections.
