### ISSUE TITLE
Status of 2.0 release

### ISSUE THREAD

**Issue by OndrejSpanel** [jsuereth/scala-arm#43]
Browsing the sources I have encountered some parts of code marked as "Preparing for 2.0 release.".

What is the status of this release? Are you still interested in it? Do you need some help?

**Comment by laughedelic** [comment]
Any updates here?

**Comment by jsuereth** [comment]
More than happy to take some help if needed.  I've been swamped with other things lately, but we should get this release out.

I think the only pending items are exposing `Try` APIs (beside existing `Option` and `Either[Seq[Exception], _]` for folks who are using Try (or working in futures).

If someone has time to think through that, I can cut the release once we have it exposed.   I'd like to do it before we lock down the 2.0 API.

**Comment by jsuereth** [comment]
Ok, so we have a 2.0-RC1 that should be on maven central, working the release notes/announcement today.

**Comment by jsuereth** [comment]
Ok, we are released.
