### ISSUE TITLE
JVM fail to load Resource class in scala-arm 2.0 with Scala 2.12.1 and JDK 8u112

### ISSUE THREAD

**Issue by njusegzyf** [jsuereth/scala-arm#57]
Using scala-arm 2.0 with Scala 2.12.1 and JDK 8u112, at runtime, the JVM failed to load the Resource class and throw an error, java.lang.NoSuchMethodError: resource.Resource.$init$(Lresource/Resource;)V

For example, when I run scala console with 
import _root_.resource.Resource
val resource : Resource[String] = new Resource[String] {
  override def close(r: String): Unit = ()
}
, a java.lang.NoSuchMethodError: resource.Resource.$init$(Lresource/Resource;)V is thrown.

**Comment by cchantep** [comment]
Hi, it was probably related to a bad mix of Scala version.
