### ISSUE TITLE
`managed` is a confusing name for C# or managed C++ developers

### ISSUE THREAD

**Issue by Atry** [jsuereth/scala-arm#61]
scala-arm's **managed** refers to a resource cannot be simply garbage-collected. However, in C#, managed means garbage-collectable.

e.g.
https://msdn.microsoft.com/en-us/library/ee787088(v=vs.110).aspx

> Managed objects automatically get clean content to start with, so their constructors do not have to initialize every data field.

**Comment by pauldraper** [comment]
"Managed" means something the lifecycle is being managed by some system. It could refer the the garbage collector, or a library like Scala ARM.
