### ISSUE TITLE
Estetic: class name typo gzipOuputStraemResource 

### ISSUE THREAD

**Issue by OndrejSpanel** [jsuereth/scala-arm#67]
One class is named `gzipOuputStraemResource`, instead of intended `gzipOuputStreamResource `. See https://github.com/jsuereth/scala-arm/blob/03a0c20bdb6e02b5cebf1bd7d6ca6f22c4d2cab2/src/main/scala/resource/Resource.scala#L110

**Comment by ianpojman** [comment]
This will be fixed if https://github.com/jsuereth/scala-arm/pull/62/commits/b41fe1b0c00fac2fbef114cd685d444fa7c87082 is merged
